In [35]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2,-3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)
features.to(device='mps')
labels.to(device='mps')

tensor([[ 1.8026e+00],
        [ 3.0969e+00],
        [ 2.2984e+00],
        [ 6.6891e+00],
        [ 5.3849e+00],
        [ 4.1852e+00],
        [ 5.2094e+00],
        [ 5.7175e+00],
        [-8.4691e-01],
        [ 7.8627e+00],
        [ 2.5879e+00],
        [ 3.0692e+00],
        [ 1.2538e+01],
        [ 4.4425e+00],
        [ 3.7065e+00],
        [ 1.2486e+01],
        [ 6.3336e+00],
        [-2.1860e+00],
        [ 3.2860e+00],
        [ 1.1677e+01],
        [ 5.4053e-01],
        [ 5.5557e+00],
        [ 3.1199e+00],
        [ 1.4145e+00],
        [ 1.5174e+00],
        [ 4.6681e+00],
        [ 1.1914e+01],
        [-2.5681e-01],
        [ 6.8853e+00],
        [ 8.4457e-01],
        [ 5.9687e+00],
        [ 4.4201e+00],
        [ 3.6060e-01],
        [ 4.4894e+00],
        [-1.8853e-01],
        [ 5.0741e+00],
        [ 4.3150e+00],
        [ 3.9933e+00],
        [ 7.2647e-01],
        [ 4.3760e+00],
        [ 6.7906e+00],
        [ 5.0581e+00],
        [ 5.3072e+00],
        [ 4

In [36]:
def load_array(data_arrays, batch_size, is_train=True):
    # 构造一个PyTorch数据迭代器
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels),batch_size)

next(iter(data_iter))

[tensor([[ 0.0521,  1.5725],
         [ 0.6237,  0.0374],
         [ 2.0599,  1.9442],
         [-1.1355, -0.5562],
         [-0.3152,  0.1748],
         [-0.8914, -0.4658],
         [-0.3099, -0.0868],
         [-0.8194,  0.1392],
         [ 0.8473,  0.2588],
         [-1.0700,  0.1614]]),
 tensor([[-1.0372],
         [ 5.3072],
         [ 1.7122],
         [ 3.8231],
         [ 2.9811],
         [ 3.9981],
         [ 3.8903],
         [ 2.0980],
         [ 5.0137],
         [ 1.5270]])]

In [37]:
from torch import nn
# list of layers
net = nn.Sequential(nn.Linear(2,1))
net.to(device='mps')

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)

In [38]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.], device='mps:0')

In [39]:
# 均方误差现成函数
loss = nn.MSELoss()
# sgd现成函数
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

In [40]:
num_epochs = 3
for epoch in range(num_epochs):
    # 小批量进行训练
    for X, y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    # 全部样本用来测试
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

RuntimeError: Tensor for argument #2 'mat1' is on CPU, but expected it to be on GPU (while checking arguments for addmm_out_mps_impl)